server:
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  resources:
    static-locations: classpath:/

  datasource:
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
